/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_wavFileReader */

#ifndef _Included_com_jni_wavFileReader
#define _Included_com_jni_wavFileReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_wavFileReader
 * Method:    loadWavAudioFile
 * Signature: (Lcom/audiomaster/plugin/AudioBufferFloat;)V
 */
JNIEXPORT void JNICALL Java_com_jni_wavFileReader_loadWavAudioFile
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jni_wavFileReader
 * Method:    saveWavAudioFile
 * Signature: (Lcom/audiomaster/plugin/AudioBufferFloat;)V
 */
JNIEXPORT void JNICALL Java_com_jni_wavFileReader_saveWavAudioFile
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
