/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_compressorJUCE */

#ifndef _Included_com_jni_compressorJUCE
#define _Included_com_jni_compressorJUCE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_compressorJUCE
 * Method:    processAndLoad
 * Signature: (Lcom/audiomaster/plugin/AudioBufferFloat;Lcom/audiomaster/plugin/compressor;)V
 */
JNIEXPORT void JNICALL Java_com_jni_compressorJUCE_processAndLoad
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
